# data/curriculum.py
# MEMORY layer — NCERT chapter maps
# Extracted from app.py (Decision 7)
# Do NOT import anthropic here. Do NOT import st here.

CURRICULUM = {
    "Science": {
        "6": [
            "Food: Where Does It Come From?",
            "Components of Food",
            "Fibre to Fabric",
            "Sorting Materials into Groups",
            "Separation of Substances",
            "Changes Around Us",
            "Getting to Know Plants",
            "Body Movements",
            "The Living Organisms and Their Surroundings",
            "Motion and Measurement of Distances",
            "Light, Shadows and Reflections",
            "Electricity and Circuits",
            "Fun with Magnets",
            "Water",
            "Air Around Us",
            "Garbage In, Garbage Out",
        ],
        "7": [
            "Nutrition in Plants",
            "Nutrition in Animals",
            "Fibre to Fabric",
            "Heat",
            "Acids, Bases and Salts",
            "Physical and Chemical Changes",
            "Weather, Climate and Adaptations",
            "Winds, Storms and Cyclones",
            "Soil",
            "Respiration in Organisms",
            "Transportation in Animals and Plants",
            "Reproduction in Plants",
            "Motion and Time",
            "Electric Current and Its Effects",
            "Light",
            "Water: A Precious Resource",
            "Forests: Our Lifeline",
            "Wastewater Story",
        ],
        "8": [
            "Crop Production and Management",
            "Microorganisms: Friend and Foe",
            "Synthetic Fibres and Plastics",
            "Materials: Metals and Non-Metals",
            "Coal and Petroleum",
            "Combustion and Flame",
            "Conservation of Plants and Animals",
            "Cell — Structure and Functions",
            "Reproduction in Animals",
            "Reaching the Age of Adolescence",
            "Force and Pressure",
            "Friction",
            "Sound",
            "Chemical Effects of Electric Current",
            "Some Natural Phenomena",
            "Light",
            "Stars and the Solar System",
            "Pollution of Air and Water",
        ],
    },
    "Mathematics": {
        "6": [
            "Knowing Our Numbers",
            "Whole Numbers",
            "Playing with Numbers",
            "Basic Geometrical Ideas",
            "Understanding Elementary Shapes",
            "Integers",
            "Fractions",
            "Decimals",
            "Data Handling",
            "Mensuration",
            "Algebra",
            "Ratio and Proportion",
            "Symmetry",
            "Practical Geometry",
        ],
        "7": [
            "Integers",
            "Fractions and Decimals",
            "Data Handling",
            "Simple Equations",
            "Lines and Angles",
            "The Triangle and Its Properties",
            "Congruence of Triangles",
            "Comparing Quantities",
            "Rational Numbers",
            "Practical Geometry",
            "Perimeter and Area",
            "Algebraic Expressions",
            "Exponents and Powers",
            "Symmetry",
            "Visualising Solid Shapes",
        ],
        "8": [
            "Rational Numbers",
            "Linear Equations in One Variable",
            "Understanding Quadrilaterals",
            "Practical Geometry",
            "Data Handling",
            "Squares and Square Roots",
            "Cubes and Cube Roots",
            "Comparing Quantities",
            "Algebraic Expressions and Identities",
            "Visualising Solid Shapes",
            "Mensuration",
            "Exponents and Powers",
            "Direct and Inverse Proportions",
            "Factorisation",
            "Introduction to Graphs",
            "Playing with Numbers",
        ],
    },
    "Social Science": {
        "6": [
            "History: What, Where, How and When?",
            "On the Trail of the Earliest People",
            "From Gathering to Growing Food",
            "In the Earliest Cities",
            "What Books and Burials Tell Us",
            "Kingdoms, Kings and an Early Republic",
            "New Questions and Ideas",
            "Ashoka, The Emperor Who Gave Up War",
            "Vital Villages, Thriving Towns",
            "Traders, Kings and Pilgrims",
            "New Empires and Kingdoms",
            "Buildings, Paintings and Books",
            "Geography: The Earth in the Solar System",
            "Globe: Latitudes and Longitudes",
            "Motions of the Earth",
            "Maps",
            "Major Domains of the Earth",
            "Major Landforms of the Earth",
            "Our Country — India",
            "India: Climate, Vegetation and Wildlife",
            "Civics: Understanding Diversity",
            "Diversity and Discrimination",
            "What is Government?",
            "Key Elements of a Democratic Government",
            "Panchayati Raj",
            "Rural Administration",
            "Urban Administration",
            "Rural Livelihoods",
            "Urban Livelihoods",
        ],
        "7": [
            "History: Tracing Changes through a Thousand Years",
            "New Kings and Kingdoms",
            "The Delhi Sultans",
            "The Mughal Empire",
            "Rulers and Buildings",
            "Towns, Traders and Craftspersons",
            "Tribes, Nomads and Settled Communities",
            "Devotional Paths to the Divine",
            "The Making of Regional Cultures",
            "Eighteenth-Century Political Formations",
            "Geography: Environment",
            "Inside Our Earth",
            "Our Changing Earth",
            "Air",
            "Water",
            "Natural Vegetation and Wildlife",
            "Human Environment — Settlement, Transport and Communication",
            "Human-Environment Interactions: The Tropical and Subtropical Region",
            "Life in the Temperate Grasslands",
            "Life in the Deserts",
            "Civics: On Equality",
            "Role of the Government in Health",
            "How the State Government Works",
            "Growing up as Boys and Girls",
            "Women Change the World",
            "Understanding Media",
            "Understanding Advertising",
            "Markets Around Us",
            "A Shirt in the Market",
        ],
        "8": [
            "History: How, When and Where",
            "From Trade to Territory",
            "Ruling the Countryside",
            "Tribals, Dikus and the Vision of a Golden Age",
            "When People Rebel — 1857 and After",
            "Colonialism and the City",
            "Weavers, Iron Smelters and Factory Owners",
            "Civilising the Native, Educating the Nation",
            "Women, Caste and Reform",
            "The Changing World of Visual Arts",
            "The Making of the National Movement: 1870s–1947",
            "India After Independence",
            "Geography: Resources",
            "Land, Soil, Water, Natural Vegetation and Wildlife Resources",
            "Mineral and Power Resources",
            "Agriculture",
            "Industries",
            "Human Resources",
            "Civics: The Indian Constitution",
            "Understanding Secularism",
            "Why Do We Need a Parliament?",
            "Understanding Laws",
            "Judiciary",
            "Understanding Our Criminal Justice System",
            "Understanding Marginalisation",
            "Confronting Marginalisation",
            "Public Facilities",
            "Law and Social Justice",
        ],
    },
    "English": {
        "6": [
            "Grammar",
            "Essay Writing",
            "Comprehension",
            "Poetry Appreciation",
            "Letter Writing",
            "Story Writing",
            "Vocabulary Building",
            "Reading Skills",
        ],
        "7": [
            "Grammar",
            "Essay Writing",
            "Comprehension",
            "Poetry Appreciation",
            "Letter Writing",
            "Story Writing",
            "Vocabulary Building",
            "Debate & Speech",
        ],
        "8": [
            "Grammar",
            "Essay Writing",
            "Comprehension",
            "Poetry Appreciation",
            "Formal Letter Writing",
            "Story Writing",
            "Vocabulary & Idioms",
            "Debate & Speech",
            "Notice & Message Writing",
        ],
    },
    "Hindi": {
        "6": [
            "व्याकरण (Grammar)",
            "निबंध लेखन (Essay)",
            "पत्र लेखन (Letter Writing)",
            "कविता (Poetry)",
            "गद्यांश (Comprehension)",
            "कहानी लेखन (Story Writing)",
            "शब्द भंडार (Vocabulary)",
        ],
        "7": [
            "व्याकरण (Grammar)",
            "निबंध लेखन (Essay)",
            "पत्र लेखन (Letter Writing)",
            "कविता (Poetry)",
            "गद्यांश (Comprehension)",
            "कहानी लेखन (Story Writing)",
            "अनुच्छेद लेखन (Paragraph)",
            "शब्द भंडार (Vocabulary)",
        ],
        "8": [
            "व्याकरण (Grammar)",
            "निबंध लेखन (Essay)",
            "पत्र लेखन (Letter Writing)",
            "कविता (Poetry)",
            "गद्यांश (Comprehension)",
            "कहानी लेखन (Story Writing)",
            "अनुच्छेद लेखन (Paragraph)",
            "विज्ञापन लेखन (Ad Writing)",
            "शब्द भंडार (Vocabulary)",
        ],
    },
}

# Subjects where chapter index doesn't apply
LANGUAGE_SUBJECTS = {"English", "Hindi"}
